Update juicer_postprocessing.sh
aidenlab/juicer pull request #282
Opened 2022-06-29 15:20 UTC by adadiehl

Expose --threads option for Arrowhead

2022-06-29 16:19 UTC, sa501428 requested changes
Can you move the threads flag to come right after the arrowhead command?

2022-06-29 16:19 UTC, sa501428 commented on CPU/common/juicer_postprocessing.sh
> +${juicer_tools_path} arrowhead ${hic_file_path} ${hic_file_path%.*}"_contact_domains" --threads ${threads}
can you move `--threads ${threads}` to come right after `arrowhead` in the line?

2022-06-29 19:10 UTC, adadiehl commented on CPU/common/juicer_postprocessing.sh
> +${juicer_tools_path} arrowhead ${hic_file_path} ${hic_file_path%.*}"_contact_domains" --threads ${threads}
Done

2022-06-29 21:00 UTC, sa501428 approved these changes

2022-06-29 21:01 UTC, merged

2022-07-07 14:45 UTC, pna059 commented
With or without the -z/--threads option postprocessing is not working:
```
$ bash ~/Juicer_dir/scripts/common/juicer_postprocessing.sh -j ~/Juicer_dir/scripts/common/juicer_tools -i aligned/inter.hic -g ~/Juicer_dir/chrom_sizes/hv03.chr.sizes
/home/pavlan/Juicer_dir/scripts/common/juicer_tools is post-processing Hi-C for /home/pavlan/Juicer_dir/chrom_sizes/hv03.chr.sizes
Data read from aligned/inter.hic.
Motifs read from /gpfs0/juicer2/references/motif

ARROWHEAD:

Exception in thread "main" jargs.gnu.CmdLineParser$IllegalOptionValueException: Illegal value 'aligned/inter.hic' for option -z/--threads
        at jargs.gnu.CmdLineParser$Option$IntegerOption.parseValue(CmdLineParser.java:202)
        at jargs.gnu.CmdLineParser$Option.getValue(CmdLineParser.java:157)
        at jargs.gnu.CmdLineParser.parse(CmdLineParser.java:485)
        at jargs.gnu.CmdLineParser.parse(CmdLineParser.java:426)
        at juicebox.tools.HiCTools.main(HiCTools.java:61)
***! Problem while running Arrowhead
```
With the option 
------------------------------------------
```
bash ~/Juicer_dir/scripts/common/juicer_postprocessing.sh -j ~/Juicer_dir/scripts/common/juicer_tools -z 10 -i aligned/inter.hic -g ~/Juicer_dir/chrom_sizes/hv03.chr.sizes/
/home/pavlan/Juicer_dir/scripts/common/juicer_postprocessing.sh: illegal option -- z
Usage: /home/pavlan/Juicer_dir/scripts/common/juicer_postprocessing.sh [-h] -j <juicer_tools_file_path> -i <hic_file_path> -m <bed_file_dir> -g <genome ID>
```

2022-07-07 15:13 UTC, adadiehl commented
Sorry, realize now I did not provide -t with a default value. Will get a
patch up ASAP.

On Thu, Jul 7, 2022 at 10:46 AM pna059 ***@***.***> wrote:

> With or without the -z/--threads option postprocessing is not working:
>
> $ bash ~/Juicer_dir/scripts/common/juicer_postprocessing.sh -j ~/Juicer_dir/scripts/common/juicer_tools -i aligned/inter.hic -g ~/Juicer_dir/chrom_sizes/hv03.chr.sizes
> /home/pavlan/Juicer_dir/scripts/common/juicer_tools is post-processing Hi-C for /home/pavlan/Juicer_dir/chrom_sizes/hv03.chr.sizes
> Data read from aligned/inter.hic.
> Motifs read from /gpfs0/juicer2/references/motif
>
> ARROWHEAD:
>
> Exception in thread "main" jargs.gnu.CmdLineParser$IllegalOptionValueException: Illegal value 'aligned/inter.hic' for option -z/--threads
>         at jargs.gnu.CmdLineParser$Option$IntegerOption.parseValue(CmdLineParser.java:202)
>         at jargs.gnu.CmdLineParser$Option.getValue(CmdLineParser.java:157)
>         at jargs.gnu.CmdLineParser.parse(CmdLineParser.java:485)
>         at jargs.gnu.CmdLineParser.parse(CmdLineParser.java:426)
>         at juicebox.tools.HiCTools.main(HiCTools.java:61)
> ***! Problem while running Arrowhead
>
> With the option
>
> bash ~/Juicer_dir/scripts/common/juicer_postprocessing.sh -j ~/Juicer_dir/scripts/common/juicer_tools -z 10 -i aligned/inter.hic -g ~/Juicer_dir/chrom_sizes/hv03.chr.sizes/
> /home/pavlan/Juicer_dir/scripts/common/juicer_postprocessing.sh: illegal option -- z
> Usage: /home/pavlan/Juicer_dir/scripts/common/juicer_postprocessing.sh [-h] -j <juicer_tools_file_path> -i <hic_file_path> -m <bed_file_dir> -g <genome ID>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/aidenlab/juicer/pull/282#issuecomment-1177730367>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACUMZSJOUHZTTUF3EGDMD6LVS3USJANCNFSM52GEAANQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>